import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const data: Record<string, [string, string, string[]]> = {
  // [soundProfile, description, features[]]
  "Audi R8 V10 Performance": ["5.2L V10 naturally aspirated — mid-engine wail, the last great Audi NA engine", "The Audi that started the supercar conversation. The R8 V10 Performance's naturally aspirated V8... V10 screams to 8,700 rpm — Lamborghini Huracán underpinnings in a daily-usable body with quattro AWD grip.", ["5.2L NA V10 620hp","8,700 RPM Redline","Quattro AWD","Magnetic Ride Suspension","Carbon Fibre Sideblades","Bang & Olufsen Sound","Virtual Cockpit","Ceramic Brake Option"]],
  "Audi RS6 Avant": ["4.0L twin-turbo V8 mild hybrid — cultured wagon thunder with sleeper aggression", "The world's greatest estate car. 630 hp from a mild-hybrid V8, air suspension, quattro AWD, and a roofline that carries bicycles, children, and a 3.4-second 0-100 time with equal composure.", ["630hp V8 MHEV","Air Suspension Standard","Quattro Sport Diff","Dynamic Ride Control","23-inch Wheel Option","Bang & Olufsen 3D Audio","Matrix LED Headlights","RS Torque Splitter"]],
  "Audi RS7 Sportback": ["4.0L twin-turbo V8 — fastback muscle car note in a four-door luxury shell", "Four-door coupé performance redefined. The RS7 Sportback delivers 630 hp in a sleek silhouette that turns every motorway into a personal autobahn — practical, devastatingly fast, and effortlessly elegant.", ["630hp V8 Sportback","Quattro AWD System","RS Sport Suspension","Predictive Active Suspension","Night Vision Assist","Heads-Up Display","21-inch Forged Wheels","Alcantara Headliner"]],
  "Audi TT RS": ["2.5L inline-5 turbo — unique 5-cylinder bark, iconic Audi motorsport soundtrack", "Five cylinders, one legend. The TT RS's 2.5L inline-5 is one of the automotive world's most distinctive engines — its uneven firing order creates a sound unlike any other production car, paired with quattro precision.", ["400hp Inline-5 Turbo","Quattro AWD","Launch Control","7-Speed S Tronic","Carbon Fibre Pack","RS Sport Exhaust","Magnetic Ride","20-inch Rotor Design Wheels"]],
  "Audi RSQ8": ["4.0L twin-turbo V8 — SUV authority with RS muscle, aggressive at full throttle", "The fastest Audi SUV ever. The RSQ8's V8 sits in the same engine bay as the Lamborghini Urus — same block, different tune — giving 600 hp in a full-size luxury SUV with air suspension and quattro AWD.", ["600hp V8 Shared with Urus","Air Suspension","Rear-Wheel Steering","23-inch Wheel Option","Sport Differential","Bang & Olufsen 3D Sound","RS Ceramic Brakes","Matrix LED with Laser"]],
  "Audi RS e-tron GT": ["Dual-motor electric — futuristic electric surge, Audi sport sound design", "The electric Audi that shares its soul with the Porsche Taycan. The RS e-tron GT produces 646 hp from dual motors, charges at 270 kW, and delivers the most refined quattro AWD experience in the electric era.", ["646hp Dual Motor AWD","270kW DC Fast Charge","Air Suspension Standard","Carbon Fibre Roof","22-inch RS Aero Wheels","Matrix LED Headlights","Bang & Olufsen Sound","Adaptive Cruise with Stop"]],
  "Rolls-Royce Phantom": ["6.75L twin-turbo V12 — whisper silent at idle, inaudible at 250 km/h, pure isolation", "The greatest car in the world. The Phantom's space-frame aluminium architecture, 130 kg of sound insulation, and Starlight Headliner make it the definitive expression of automotive luxury — nothing comes close.", ["130kg Sound Insulation","Starlight Headliner","Gallery Dashboard","6.75L Twin-Turbo V12","Self-Closing Doors","Four-Zone Climate","Bespoke Audio System","Coach Line Personalisation"]],
  "Rolls-Royce Ghost": ["6.75L twin-turbo V12 — imperceptible power, post-opulence silence as a philosophy", "The Ghost that learned to whisper. The Architecture of Luxury — all-aluminium space frame — makes the Ghost the quietest car Rolls-Royce has ever built, redefining post-opulence for a generation that values restraint.", ["Architecture of Luxury Platform","Flagbearer Headlights","Illuminated Fascia","4D Massage Seats","Bespoke Audio 18 Speakers","All-Wheel Drive Standard","Night Vision","Rear Theatre Config"]],
  "Rolls-Royce Cullinan Black Badge": ["6.75L twin-turbo V12 SUV — dark alter-ego thunder, 600hp effortless authority", "The anti-Rolls-Royce Rolls-Royce. Black Badge darkens every chrome element, extracts 600 hp from the V12, and recalibrates the suspension for a more spirited character — for those who find the standard Cullinan too reserved.", ["600hp Black Badge V12","All-Chrome Deleted","Black Starlight Headliner","Self-Levelling Air Suspension","Night Vision Assist","Bespoke Black Audio","22-inch Carbon Wheels","Shooting Star Headliner"]],
  "Rolls-Royce Dawn": ["6.75L twin-turbo V12 soft-top — the most silent convertible on earth, open-air luxury", "The most silent open-top car ever built. The Dawn's triple-layer insulated hood and acoustic side windows keep the V12 refined even with the roof down — a convertible for those who believe luxury should never compromise.", ["Triple-Layer Insulated Hood","8-Second Power Hood","6.75L Twin-Turbo V12","Seats for Four Adults","Starlight Interior Option","Waterfall Centre Console","Bespoke Luggage Set","Gallery Audio System"]],
  "Rolls-Royce Wraith": ["6.75L twin-turbo V12 coupe — fastback grand tourer with satellite-aided gearbox", "The most powerful Rolls-Royce coupé. The Wraith's satellite-aided transmission reads GPS data to select the right gear for upcoming bends — a genuinely intelligent drivetrain matched to a fastback silhouette of dramatic presence.", ["632hp Twin-Turbo V12","GPS Satellite Gearbox","Starlight Headliner","Fastback Roofline","Bespoke Audio 18-Speaker","Coach Doors","Power-Close Doors","Carbon Fibre Option"]],
  "Rolls-Royce Spectre": ["Dual-motor electric V12 substitute — imperceptible EV silence, Rolls-Royce reimagined", "The first electric Rolls-Royce. The Spectre carries 430 kg of batteries yet rides on the Architecture of Luxury platform — generating 585 hp in near-absolute silence, with 500 km of range and the quietest interior ever measured.", ["585hp Dual Motor AWD","500km+ Range","Architecture of Luxury","Illuminated Grille Option","Flagbearer Headlights","Bespoke Lounge Interior","22-inch Aero Wheels","Active Noise Cancellation"]],
  "Bentley Continental GT Speed": ["6.0L W12 twin-turbo — the most characterful GT note on earth, cultured thunder", "The fastest and most driver-focused Bentley ever. The Continental GT Speed has rear-wheel steering, an electronic rear differential, and 659 hp from the legendary W12 — a GT car with the soul of a sports car.", ["659hp W12 Twin-Turbo","Rear-Wheel Steering","Electronic Rear Diff","Carbon Ceramic Brakes","Rotating Display","Diamond-Knurled Surfaces","Naim for Bentley Audio","21-inch Speed Wheels"]],
  "Bentley Flying Spur Mulliner": ["6.0L W12 — limousine comfort with 635hp GT performance, finest Bentley expression", "Mulliner is Bentley's in-house bespoke division. The Flying Spur Mulliner adds three-dimensional diamond quilting, a Mulliner clock, and Bentley's most refined interior touches to the W12's continent-crushing performance.", ["Mulliner Bespoke Interior","3D Diamond Quilting","Mulliner Tourbillon Clock","All-Wheel Drive + Steer","635hp W12","Naim for Bentley Audio","Rear Executive Seats","Night Vision Assist"]],
  "Bentley Bacalar": ["6.0L W12 twin-turbo open barchetta — rarest Bentley thunder, 12 exist", "The rarest Bentley in history. Only 12 Bacalars were ever built, each a bespoke open barchetta with no roof, no windscreen, and the W12's full 650 hp. Named after Lake Bacalar in Mexico, each one is unique to its owner.", ["Only 12 Units Built","Open Barchetta No Roof","650hp W12","Sustainable Materials Option","Hand-Formed Bodywork","Bentley Mulliner Design","5,000-Year-Old Wood Trim","Named After Lake Bacalar"]],
  "Bentley Batur": ["6.0L W12 — 730hp most powerful Bentley ever in a Mulliner design study", "The most powerful Bentley ever built. The Batur's W12 produces 730 hp — previewing the design language of Bentley's electric future while celebrating the final chapter of the iconic W12 engine era.", ["730hp Most Powerful Bentley","18 Units Only","Mulliner Coachbuilt","New Design Language Preview","Sustainable Interior Materials","Carbon Fibre Bodywork","Rotating Display","Bentley 3D Knurling"]],
  "Bentley Bentayga S": ["4.0L twin-turbo V8 — sport-tuned Bentayga bark, sharpest Bentayga character", "The sports driver's Bentayga. The Bentayga S lowers the suspension by 15 mm, adds 48V active anti-roll, and retuned the V8 for a more immediate throttle response — without sacrificing the Bentayga's capability.", ["550hp V8 Sport Tune","15mm Lower Suspension","48V Active Anti-Roll","Sport Exhaust Standard","21-inch S Wheels","Carbon Exterior Pack","Alcantara Headliner","Drive Dynamics Mode"]],
  "Maserati MC20": ["3.0L twin-turbo Nettuno V6 — Formula 1 pre-chamber tech, crisp Italian sprint car", "The rebirth of Maserati's racing soul. The MC20's Nettuno engine uses Formula 1-derived pre-chamber combustion technology — 630 hp from a 3.0L V6 in a mid-engine carbon monocoque that weighs just 1,500 kg.", ["630hp Nettuno F1-Tech V6","Pre-Chamber Combustion","Carbon Fibre Monocoque","Butterfly Doors","1,500kg Dry Weight","Brembo Carbon Brakes","Sonus Faber Audio","Maserati Corse Mode"]],
  "Maserati GranTurismo Trofeo": ["3.0L twin-turbo Nettuno V6 — sport GT howl, Italian elegance with real performance", "The GranTurismo reborn with the MC20's engine. The Trofeo version takes the Nettuno V6 to 550 hp in a long-bonnet GT body of Italian artistry — a 2+2 coupé that covers roads with effortless Latin authority.", ["550hp Nettuno V6","MC20-Derived Engine","Sonus Faber Audio","Carbon Fibre Details","2+2 GT Layout","Air Suspension","Maserati Drive Modes","19-inch Forged Wheels"]],
  "Maserati Levante Trofeo": ["3.8L twin-turbo Ferrari V8 — Ferrari engine in a Maserati SUV, exceptional soundtrack", "The only SUV with a Ferrari V8. The Levante Trofeo borrows its 580 hp engine directly from the Ferrari engine plant at Maranello — making it the most sonically exciting luxury SUV ever produced.", ["580hp Ferrari-Built V8","Ferrari Maranello Engine","Q4 AWD System","Skyhook Suspension","Brembo Brakes","Harman Kardon Audio","21-inch Forged Wheels","Zegna Interior Option"]],
  "Maserati Grecale Folgore": ["Dual-motor electric — instant SUV torque, Maserati enters the electric era", "Maserati's electric future arrives. The Grecale Folgore produces 557 hp from dual motors in a premium compact SUV — fast-charging, rear-biased AWD, and a Maserati interior calibrated for the next generation of luxury.", ["557hp Dual Motor EV","Fast Charge 150kW","Rear-Biased AWD","Sonus Faber Audio","22-inch Wheels","Folgore Sport Mode","Over-the-Air Updates","Maserati Connect App"]],
  "Maserati Quattroporte GTS": ["3.8L twin-turbo Ferrari V8 — sports saloon fury, Ferrari engine in four-door grace", "The fastest four-door saloon Maserati ever built. The Quattroporte GTS puts 530 hp from a Ferrari-built twin-turbo V8 into a long-wheelbase luxury saloon — a combination of Italian elegance and visceral performance.", ["530hp Ferrari V8","Long-Wheelbase Luxury","Skyhook Adaptive Damping","Q4 AWD System","Bowers & Wilkins Audio","Poltrona Frau Leather","21-inch Forged Wheels","Maserati Sport Mode"]],
  "Lexus LFA": ["4.8L V10 naturally aspirated — Yamaha-tuned operatic scream, one of the greatest sounds ever recorded", "The greatest Japanese supercar ever made. The LFA's V10 revs so fast that Lexus had to use a digital tachometer — the needle moved faster than an analogue gauge could follow. Yamaha tuned the exhaust note as a musical instrument.", ["72hp V10 Yamaha-Tuned Sound","Digital Tachometer Only","Carbon Fibre Monocoque","Only 500 Units Built","Öhlins Suspension","Brembo Carbon Ceramic","Lexus F Performance DNA","Hand-Assembled V10"]],
  "Lexus LC500": ["5.0L naturally aspirated V8 — deep, melodic Japanese V8 rumble with quad exhausts", "Japan's luxury grand tourer. The LC500's 5.0L V8 is one of the last great naturally aspirated engines — paired with a 10-speed automatic that snaps through gears with precision, in a body sculpted as moving art.", ["5.0L NA V8 477hp","10-Speed Direct-Shift Auto","Torsen Limited-Slip Diff","Yamaha-Tuned Exhaust","21-inch Forged Wheels","Mark Levinson Audio","Carbon Fibre Roof Option","Structural Body Reinforcement"]],
  "Lexus RC F Track Edition": ["5.0L naturally aspirated V8 — track-spec V8 howl, 60kg lighter than standard RC F", "Lexus's answer to the M4 Competition. The RC F Track Edition sheds 60 kg through carbon fibre everywhere — roof, rear wing, drive shaft — and adds Brembo carbon ceramic brakes and Michelin Cup 2 tyres for track-day supremacy.", ["474hp NA V8","60kg Track Weight Reduction","Carbon Fibre Drive Shaft","Brembo Carbon Ceramic","Michelin Pilot Cup 2","Carbon Fibre Roof","Fixed Carbon Rear Wing","Torsen LSD"]],
  "Lexus IS500 F Sport": ["5.0L naturally aspirated V8 — naturally aspirated surprise in a compact sport saloon", "An unexpected V8 in a segment full of turbocharged sixes. The IS500 puts Lexus's 472 hp naturally aspirated V8 into the IS bodyshell — rear-wheel drive, active rear steering, and a soundtrack no turbo six can replicate.", ["472hp NA V8 RWD","Active Rear Steering","Launch Control","21-inch F Sport Wheels","Torsen Limited-Slip Diff","Mark Levinson Audio","Adaptive Variable Suspension","Performance Exhaust"]],
  "Lexus LX600": ["3.5L twin-turbo V6 — premium Japanese SUV authority, refined and commanding", "Lexus takes the Land Cruiser further. The LX600 adds a premium twin-turbo V6, a four-seat executive configuration with rear captain's chairs, and 48V mild hybrid technology in a body built for luxury and genuine off-road capability.", ["416hp Twin-Turbo V6","48V Mild Hybrid","Crawl Control","Multi-Terrain Monitor","Mark Levinson 25-Speaker","4-Seat Executive Config","Semi-Aniline Leather","Digital Terrain Monitor"]],
  "Tesla Roadster": ["Quad-motor electric — SpaceX cold gas thruster option, 0-100 in 1.1 seconds", "The car that made the world take electric vehicles seriously, reborn. The new Roadster produces over 1,000 hp from four electric motors with an optional SpaceX cold gas thruster package — targeting 0-100 km/h in 1.1 seconds.", ["1000hp+ Quad Motor EV","SpaceX Thruster Package Option","1.1s 0-100 Target","Glass Roof Storage","All-Wheel Drive","250mph Target Top Speed","Over-the-Air Updates","Removable Glass Roof"]],
  "Tesla Cybertruck Cyberbeast": ["Triple-motor electric — 845hp dystopian truck, instant torque in an exoskeleton body", "Steel doesn't bend — it's the whole point. The Cybertruck's exoskeleton stainless steel body resists dents and scratches while its Cyberbeast tri-motor system hits 100 km/h in 2.6 seconds. Nothing else looks, feels, or drives like it.", ["845hp Tri-Motor AWD","Stainless Steel Exoskeleton","2.6s 0-100 km/h","Air Suspension Adaptive","Armour Glass","800V Architecture","Full Self-Driving Capable","Camp Mode + Power Outlet"]],
  "Tesla Model X Plaid": ["Tri-motor electric — 1,020hp silent family SUV, Ludicrous+ mode physics", "The quickest SUV on the planet. The Model X Plaid's tri-motor system produces 1,020 hp — in a seven-seat SUV with Falcon Wing doors, a 17-inch cinema display, and the practicality to carry a surfboard in the boot.", ["1020hp Tri-Motor AWD","Falcon Wing Rear Doors","17-inch Cinematic Screen","7-Seat Configuration","HEPA Air Filtration","Autopilot + FSD","500km+ Range","Bioweapon Defense Mode"]],
  "Chevrolet Corvette Z06": ["5.5L flat-plane V8 naturally aspirated — Ferrari-rivalling 8,600rpm American scream", "America builds a Ferrari rival. The Z06's LT6 engine is the most powerful naturally aspirated V8 ever fitted to a production car — 670 hp at 8,400 rpm in a mid-engine Corvette with magnetic ride and carbon fibre everywhere.", ["670hp NA Flat-Plane V8","8,400 RPM Redline","Mid-Engine Layout","Magnetic Ride 4.0","Carbon Fibre Aero Package","Brembo Carbon Ceramic","Michelin Pilot Cup 2","Z07 Performance Package"]],
  "Chevrolet Corvette E-Ray": ["5.5L V8 + electric front motor — hybrid American muscle with e-AWD precision", "America's first all-wheel-drive Corvette. The E-Ray adds an electric motor to the front axle, giving the Stingray's V8 instant AWD traction — 655 hp total, 0-100 in 2.5 seconds, and the ability to drive silently on electric alone.", ["655hp Hybrid V8 AWD","Electric Front Axle","Silent EV Stealth Mode","2.5s 0-100 km/h","Magnetic Ride Suspension","Performance Data Recorder","Brembo Brakes","Z51 Performance Package"]],
  "Chevrolet Camaro ZL1": ["6.2L supercharged LT4 V8 — American muscle roar, supercharger whine at full throttle", "Detroit's muscle car taken to its logical extreme. The ZL1's supercharged LT4 V8 produces 650 hp — Camaro's most powerful engine ever — with a magnetic ride suspension and a 10-speed automatic that can lap Nürburgring.", ["650hp Supercharged LT4 V8","Supercharger Whine On Boost","Magnetic Ride Suspension","Brembo 6-Piston Brakes","Performance Data Recorder","Recaro Sport Seats","Electronic LSD","1LE Track Package Option"]],
  "Ford GT": ["3.5L EcoBoost twin-turbo V6 — Le Mans race car soundtrack for the road", "The car that beat Ferrari at Le Mans in 2016 — 50 years after the original. The Ford GT's twin-turbo V6 and carbon monocoque were developed from its Le Mans race programme. Each GT is a direct descendant of a race winner.", ["647hp Le Mans-Derived V6","Carbon Fibre Monocoque","Active Rear Wing","Flying Buttress Bodywork","Le Mans Heritage Livery","Only 1,350 Built","Push-Rod Suspension","Hydraulic Steering"]],
  "Ford Mustang Dark Horse": ["5.0L Coyote V8 naturally aspirated — Mustang's sharpest V8 note, track-tuned character", "The most track-focused production Mustang ever. The Dark Horse extracts 500 hp from the naturally aspirated Coyote V8, adds Brembo brakes, a Torsen rear diff, and a handling pack that finally makes the Mustang a credible track car.", ["500hp NA Coyote V8","Brembo Performance Brakes","Torsen Limited-Slip Diff","Carbon Fibre Track Pack","Dark Horse Handling Pack","6-Speed Manual Option","MagneRide Suspension","Launch Control"]],
  "Ford Shelby GT500": ["5.2L supercharged flat-plane V8 — most powerful Ford ever, supercharger howl", "760 hp. The most powerful street-legal Ford vehicle ever produced. The GT500's flat-plane crank V8 with supercharger produces an other-worldly sound, and the Carbon Fibre Track Pack makes it genuinely circuit-capable.", ["760hp Supercharged V8","Flat-Plane Crank NA-Feel","Carbon Fibre Track Pack","Michelin Pilot Sport 4S","MagneRide 2.0 Suspension","6-Speed Tremec Manual","Brembo 6-Piston Brakes","Electronic Line-Lock"]],
  "Dodge Challenger Demon 170": ["6.2L supercharged Hellcat HEMI V8 — drag strip monster, 1,025hp on E85 pure fury", "The most powerful muscle car ever built. On E85 fuel, the Demon 170 produces 1,025 hp — enough for a 8.91-second quarter mile. It comes with a drag racing app, front lift, and one front passenger seat (the second is optional).", ["1025hp on E85 Fuel","8.91s Quarter Mile Stock","Drag Mode Suspension","SRT PowerShare Outlets","Demon 170 Track App","Nitto NT05R Drag Tires","One Passenger Seat Stock","Last V8 Challenger"]],
  "Dodge Viper ACR": ["8.4L V10 naturally aspirated — raw American V10 scream, no electronic coddling", "The most track-capable street car Dodge ever built. The Viper ACR uses a 645 hp V10 with no stability control, extreme aero generating 680 kg of downforce, and Michelin Pilot Sport Cup 2 tyres — a car for serious drivers only.", ["645hp 8.4L NA V10","680kg Downforce","No Stability Control Standard","Extreme Aero Package","Bilstein Dampers","Brembo Carbon Ceramic","Michelin Cup 2 Tires","ACR Lap Record Holder"]],
  "Dodge Charger Hellcat Redeye": ["6.2L supercharged HEMI V8 — 797hp muscle car thunder, widebody fury", "The world's most powerful and fastest mass-produced sedan. 797 hp from a supercharged HEMI V8 in a four-door widebody — the Charger Hellcat Redeye makes no apologies and takes no prisoners.", ["797hp Supercharged HEMI","Widebody Fenders","Launch Control","Line Lock Burnout Mode","SRT Performance Pages","Harman Kardon Audio","Brembo 6-Piston Brakes","Demon-Spec Supercharger"]],
  "Nissan GT-R Nismo": ["3.8L twin-turbo V6 — Godzilla's final form, precision Japanese turbo howl", "Godzilla upgraded by Nismo. The GT-R Nismo uses hand-assembled engines from Takumi craftsmen, chassis tuned at Nürburgring, and aerodynamics derived from Nissan's GT3 programme. The original everyday supercar, perfected.", ["600hp Hand-Built VR38DETT","Nürburgring Chassis Tune","GT3-Derived Aero","Bilstein DampTronic","Brembo Carbon Ceramic","Recaro Carbon Seats","Launch Control 3.0","Gran Turismo Heritage"]],
  "Nissan Z Nismo": ["3.0L twin-turbo V6 — JDM sport coupe bark, lightweight and revvy character", "The Z Nismo brings the Z's twin-turbo V6 to its sharpest specification — 420 hp, larger Brembo brakes, Nismo-tuned suspension, and a Rays forged wheel package that reduces unsprung weight. Japan's most focused sports coupe.", ["420hp Twin-Turbo V6","Brembo Performance Brakes","Rays Forged Wheels","Nismo Suspension Tune","Recaro Sport Seats","Nismo Aerodynamics Kit","Limited-Slip Differential","6-Speed Manual Standard"]],
  "Ford Bronco Raptor": ["3.0L twin-turbo EcoBoost V6 — off-road thunder, 418hp desert racing character", "The most off-road capable production Bronco ever built. The Bronco Raptor uses Fox Live Valve suspension with 13 inches of travel, 37-inch tyres from the factory, and a twin-turbo V6 tuned for desert racing performance.", ["418hp Twin-Turbo V6","37-inch Factory Tires","Fox Live Valve Suspension","13-Inch Suspension Travel","Portal Axles","Desert Racer Inspiration","Bead-Lock Capable Wheels","Trail Turn Assist"]],
};

async function main() {
  let ok = 0, miss = 0;
  for (const [name, [s, d, f]] of Object.entries(data)) {
    const car = await prisma.car.findFirst({ where: { name } });
    if (!car) { console.log(`⚠️  ${name}`); miss++; continue; }
    await prisma.car.update({ where: { id: car.id }, data: { soundProfile: s, description: d, features: JSON.stringify(f) } });
    console.log(`✅ ${name}`);
    ok++;
  }
  console.log(`\n✅ ${ok}  ⚠️  ${miss}`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
